/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeli4m.lab02;

/**
 *
 * @author HP
 */
public class EmpleadoGUI extends javax.swing.JFrame {
    private String codigo;
    private String nombre;
    private String area;
    double sueldoBase;
    double horasExtras;
    private String tipo_seg;
    Empleado emp = new Empleado("","","",0f,0f,"");

    /**
     * Creates new form EmpleadoGUI
     */
    public EmpleadoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSueldoBase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHorasExtras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxArea = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoSeguro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEmpleadoInfo = new javax.swing.JTextArea();
        jButtonCrearObjeto = new javax.swing.JButton();
        jButtonMostrarInformacion = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar empleado");
        setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));

        jTextFieldCodigo.setBackground(new java.awt.Color(221, 221, 221));
        jTextFieldCodigo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(34, 40, 49));
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCodigo.setToolTipText("Codigo del empleado");
        jTextFieldCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCodigo.setCaretColor(new java.awt.Color(34, 40, 49));
        jTextFieldCodigo.setMinimumSize(new java.awt.Dimension(20, 26));
        jTextFieldCodigo.setPreferredSize(new java.awt.Dimension(18, 26));
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("CODIGO");

        jTextFieldSueldoBase.setBackground(new java.awt.Color(221, 221, 221));
        jTextFieldSueldoBase.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextFieldSueldoBase.setForeground(new java.awt.Color(34, 40, 49));
        jTextFieldSueldoBase.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldSueldoBase.setToolTipText("Sueldo base del empleado");
        jTextFieldSueldoBase.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldSueldoBase.setCaretColor(new java.awt.Color(34, 40, 49));
        jTextFieldSueldoBase.setMinimumSize(new java.awt.Dimension(20, 26));
        jTextFieldSueldoBase.setPreferredSize(new java.awt.Dimension(18, 26));
        jTextFieldSueldoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSueldoBaseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("SUELDO BASE");

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("NOMBRE COMPLETO");

        jTextFieldNombreCompleto.setBackground(new java.awt.Color(221, 221, 221));
        jTextFieldNombreCompleto.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextFieldNombreCompleto.setForeground(new java.awt.Color(34, 40, 49));
        jTextFieldNombreCompleto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNombreCompleto.setToolTipText("Nombre completo. Nombres y apellidos");
        jTextFieldNombreCompleto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldNombreCompleto.setCaretColor(new java.awt.Color(34, 40, 49));
        jTextFieldNombreCompleto.setMinimumSize(new java.awt.Dimension(20, 26));
        jTextFieldNombreCompleto.setPreferredSize(new java.awt.Dimension(18, 26));
        jTextFieldNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCompletoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("HORAS EXTRAS");

        jTextFieldHorasExtras.setBackground(new java.awt.Color(221, 221, 221));
        jTextFieldHorasExtras.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextFieldHorasExtras.setForeground(new java.awt.Color(34, 40, 49));
        jTextFieldHorasExtras.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldHorasExtras.setToolTipText("Cantidad de horas extras");
        jTextFieldHorasExtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldHorasExtras.setCaretColor(new java.awt.Color(34, 40, 49));
        jTextFieldHorasExtras.setMinimumSize(new java.awt.Dimension(20, 26));
        jTextFieldHorasExtras.setPreferredSize(new java.awt.Dimension(18, 26));
        jTextFieldHorasExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasExtrasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("TIPO SEGURO");

        jComboBoxArea.setBackground(new java.awt.Color(58, 71, 94));
        jComboBoxArea.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBoxArea.setForeground(java.awt.Color.white);
        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Administracion", "Marketing" }));
        jComboBoxArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxArea.setDoubleBuffered(true);

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("AREA");

        jComboBoxTipoSeguro.setBackground(new java.awt.Color(58, 71, 94));
        jComboBoxTipoSeguro.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBoxTipoSeguro.setForeground(java.awt.Color.white);
        jComboBoxTipoSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AFP", "SNP" }));
        jComboBoxTipoSeguro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextAreaEmpleadoInfo.setEditable(false);
        jTextAreaEmpleadoInfo.setBackground(new java.awt.Color(223, 223, 223));
        jTextAreaEmpleadoInfo.setColumns(20);
        jTextAreaEmpleadoInfo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextAreaEmpleadoInfo.setForeground(new java.awt.Color(34, 40, 49));
        jTextAreaEmpleadoInfo.setRows(5);
        jTextAreaEmpleadoInfo.setText("\n");
        jTextAreaEmpleadoInfo.setAutoscrolls(false);
        jTextAreaEmpleadoInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 14, 12, 14));
        jScrollPane1.setViewportView(jTextAreaEmpleadoInfo);

        jButtonCrearObjeto.setBackground(new java.awt.Color(240, 84, 84));
        jButtonCrearObjeto.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jButtonCrearObjeto.setForeground(java.awt.Color.white);
        jButtonCrearObjeto.setText("CREAR OBJETO");
        jButtonCrearObjeto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jButtonCrearObjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearObjetoActionPerformed(evt);
            }
        });

        jButtonMostrarInformacion.setBackground(new java.awt.Color(240, 84, 84));
        jButtonMostrarInformacion.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jButtonMostrarInformacion.setForeground(java.awt.Color.white);
        jButtonMostrarInformacion.setText("MOSTRAR INFORMACION");
        jButtonMostrarInformacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jButtonMostrarInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMostrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarInformacionActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(240, 84, 84));
        jButtonLimpiar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jButtonLimpiar.setForeground(java.awt.Color.white);
        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8)));
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.setOpaque(false);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(240, 84, 84));
        jButtonSalir.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jButtonSalir.setForeground(java.awt.Color.white);
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8)));
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.setOpaque(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCrearObjeto)
                        .addGap(24, 24, 24)
                        .addComponent(jButtonMostrarInformacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar)
                        .addGap(24, 24, 24)
                        .addComponent(jButtonSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBoxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldSueldoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSueldoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSueldoBaseActionPerformed

    private void jTextFieldNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCompletoActionPerformed

    private void jTextFieldHorasExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasExtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorasExtrasActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        emp = new Empleado("","","",0f,0f,"");
        jTextFieldCodigo.setText("");
        jTextAreaEmpleadoInfo.setText("");
        jTextFieldHorasExtras.setText("");
        jTextFieldNombreCompleto.setText("");
        jTextFieldSueldoBase.setText("");
        jComboBoxArea.setSelectedIndex(0);
        jComboBoxArea.setSelectedIndex(0);
        jTextFieldCodigo.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonCrearObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearObjetoActionPerformed
        // TODO add your handling code here:
        String inputCodigo = jTextFieldCodigo.getText();
        String inputName = jTextFieldNombreCompleto.getText();
        String inputTipoSeguro = jComboBoxTipoSeguro.getSelectedItem().toString();
        String inputArea = jComboBoxArea.getSelectedItem().toString();        
        String inputSueldoBase = jTextFieldSueldoBase.getText();
        String inputHorasExtras = jTextFieldHorasExtras.getText();
        emp = new Empleado(inputCodigo, inputName, inputArea, Double.parseDouble(inputSueldoBase), Double.parseDouble(inputHorasExtras), inputTipoSeguro);
        

    }//GEN-LAST:event_jButtonCrearObjetoActionPerformed

    private void jButtonMostrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarInformacionActionPerformed
        // TODO add your handling code here:
        String empleadoInfo = emp.getEmpleadoFullInfo();
        System.out.println("EMPLEADO INFO");
        jTextAreaEmpleadoInfo.setText(empleadoInfo);
    }//GEN-LAST:event_jButtonMostrarInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButtonCrearObjeto;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMostrarInformacion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxArea;
    private javax.swing.JComboBox<String> jComboBoxTipoSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEmpleadoInfo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldHorasExtras;
    private javax.swing.JTextField jTextFieldNombreCompleto;
    private javax.swing.JTextField jTextFieldSueldoBase;
    // End of variables declaration//GEN-END:variables
}
