/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sem1_ciclo2;

import javax.sound.midi.MidiUnavailableException;

/**
 *
 * @author HP
 */
public class Sem1_ciclo2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Sem1_ciclo2() {
        initComponents();
    }
    
    public float value1 = 0f;
    public float value2 = 0f;
    public float substraction = 0;
    public float addition = 0;
    public float multiplication = 0;
    public float divition = 0;
    String valueString1;
    String valueString2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*SuppressWarnings ("unchecked");*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValue1 = new javax.swing.JTextField();
        jTextFieldValue2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldResultAddition = new javax.swing.JTextField();
        jTextFieldResultSubstraction = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldResultMultiplication = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldResultDivision = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("OPERACIONES ARITMETICAS");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Valor 1:");

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Valor 2:");

        jTextFieldValue1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValue1.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextFieldValue1.setForeground(new java.awt.Color(44, 51, 51));
        jTextFieldValue1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldValue1.setCaretColor(new java.awt.Color(44, 51, 51));
        jTextFieldValue1.setMinimumSize(new java.awt.Dimension(6, 24));
        jTextFieldValue1.setSelectedTextColor(new java.awt.Color(4, 4, 4));
        jTextFieldValue1.setSelectionColor(new java.awt.Color(44, 51, 51));
        jTextFieldValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValue1ActionPerformed(evt);
            }
        });

        jTextFieldValue2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValue2.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextFieldValue2.setForeground(new java.awt.Color(44, 51, 51));
        jTextFieldValue2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldValue2.setCaretColor(new java.awt.Color(44, 51, 51));
        jTextFieldValue2.setMinimumSize(new java.awt.Dimension(6, 24));
        jTextFieldValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValue2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Suma:");

        jTextFieldResultAddition.setEditable(false);
        jTextFieldResultAddition.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultAddition.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextFieldResultAddition.setForeground(new java.awt.Color(44, 51, 51));
        jTextFieldResultAddition.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldResultAddition.setCaretColor(new java.awt.Color(44, 51, 51));
        jTextFieldResultAddition.setMinimumSize(new java.awt.Dimension(6, 24));
        jTextFieldResultAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultAdditionActionPerformed(evt);
            }
        });

        jTextFieldResultSubstraction.setEditable(false);
        jTextFieldResultSubstraction.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultSubstraction.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextFieldResultSubstraction.setForeground(new java.awt.Color(44, 51, 51));
        jTextFieldResultSubstraction.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldResultSubstraction.setCaretColor(new java.awt.Color(44, 51, 51));
        jTextFieldResultSubstraction.setMinimumSize(new java.awt.Dimension(6, 24));
        jTextFieldResultSubstraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultSubstractionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Resta:");

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Muliplicacion:");

        jTextFieldResultMultiplication.setEditable(false);
        jTextFieldResultMultiplication.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultMultiplication.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextFieldResultMultiplication.setForeground(new java.awt.Color(44, 51, 51));
        jTextFieldResultMultiplication.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldResultMultiplication.setCaretColor(new java.awt.Color(44, 51, 51));
        jTextFieldResultMultiplication.setMinimumSize(new java.awt.Dimension(6, 24));
        jTextFieldResultMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultMultiplicationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Division:");

        jTextFieldResultDivision.setEditable(false);
        jTextFieldResultDivision.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultDivision.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextFieldResultDivision.setForeground(new java.awt.Color(44, 51, 51));
        jTextFieldResultDivision.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldResultDivision.setCaretColor(new java.awt.Color(44, 51, 51));
        jTextFieldResultDivision.setMinimumSize(new java.awt.Dimension(6, 24));
        jTextFieldResultDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultDivisionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("RESULTADOS");

        jButtonClear.setBackground(new java.awt.Color(254, 177, 57));
        jButtonClear.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jButtonClear.setForeground(java.awt.Color.white);
        jButtonClear.setText("LIMPIAR");
        jButtonClear.setBorder(null);
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCalculate.setBackground(new java.awt.Color(245, 83, 83));
        jButtonCalculate.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jButtonCalculate.setForeground(java.awt.Color.white);
        jButtonCalculate.setText("CALCULAR");
        jButtonCalculate.setBorder(null);
        jButtonCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(24, 24, 24)
                                        .addComponent(jTextFieldResultAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldResultSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldResultDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldResultMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldResultAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldResultMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldResultSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldResultDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValue1ActionPerformed

    private void jTextFieldValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValue2ActionPerformed

    private void jTextFieldResultAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultAdditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultAdditionActionPerformed

    private void jTextFieldResultSubstractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultSubstractionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultSubstractionActionPerformed

    private void jTextFieldResultMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultMultiplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultMultiplicationActionPerformed

    private void jTextFieldResultDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultDivisionActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldResultAddition.setText("");
        jTextFieldResultDivision.setText("");
        jTextFieldResultMultiplication.setText("");
        jTextFieldResultSubstraction.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:

        valueString1 = jTextFieldValue1.getText();
        valueString2 = jTextFieldValue2.getText();
        value1 = Float.parseFloat(valueString1);
        value2 = Float.parseFloat(valueString2);
        addition = value1 + value2;
        substraction = value1 - value2;
        multiplication = value1 * value2;
        divition = value1 / value2;
        
        jTextFieldResultAddition.setText(Float.toString(addition));
        jTextFieldResultDivision.setText(Float.toString(divition));
        jTextFieldResultMultiplication.setText(Float.toString(multiplication));
        jTextFieldResultSubstraction.setText(Float.toString(substraction));
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sem1_ciclo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sem1_ciclo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sem1_ciclo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sem1_ciclo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sem1_ciclo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldResultAddition;
    private javax.swing.JTextField jTextFieldResultDivision;
    private javax.swing.JTextField jTextFieldResultMultiplication;
    private javax.swing.JTextField jTextFieldResultSubstraction;
    private javax.swing.JTextField jTextFieldValue1;
    private javax.swing.JTextField jTextFieldValue2;
    // End of variables declaration//GEN-END:variables
}
