/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeli4m.ejemplosem5;

/**
 *
 * @author HP
 */
public class CalculatorInterface extends javax.swing.JFrame {

    Calculator calc = new Calculator();
    
    
//    String firstValueString = "";
//    String secondValueString = "";
    String displayText = "";
    String currentOperation = "";
    /**
     * Creates new form CalculatorInterface
     */
    public CalculatorInterface() {
        initComponents();
    }

    
    private void updateDisplayValue(){
        this.jTextFieldDisplay.setText(this.displayText);
    }
    
    private void dynamicChangeDisplayValue(String value){
        // TODO: check only oe operation per display
        this.displayText += value;
        this.jTextFieldOperationProcess.setText("");
        updateDisplayValue();
    }
    
    private void clearScreenValues(){
        this.displayText = "";
        this.jTextFieldDisplay.setText("");
        this.jTextFieldOperationProcess.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldOperationProcess = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonSymbolClearEverything = new javax.swing.JButton();
        jButtonSymbolClear = new javax.swing.JButton();
        jButtonSymbolErase = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();
        jButtonNumberFour = new javax.swing.JButton();
        jButtonNumberFive = new javax.swing.JButton();
        jButtonNumberSix = new javax.swing.JButton();
        jButtonSymbolMinus = new javax.swing.JButton();
        jButtonNumberSeven = new javax.swing.JButton();
        jButtonNumberEight = new javax.swing.JButton();
        jButtonNumberNine = new javax.swing.JButton();
        jButtonSymbolMultiplication = new javax.swing.JButton();
        jButtonSymbolMpdule = new javax.swing.JButton();
        jButtonSymbolPowTwo = new javax.swing.JButton();
        jButtonSymbolPow = new javax.swing.JButton();
        jButtonSymbolDivition = new javax.swing.JButton();
        jButtonNumberOne = new javax.swing.JButton();
        jButtonNumberTwo = new javax.swing.JButton();
        jButtonNumberThree = new javax.swing.JButton();
        jButtonSymbolPlus = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButtonNumberZero = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButtonSymbolEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jTextFieldOperationProcess.setEditable(false);
        jTextFieldOperationProcess.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldOperationProcess.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldOperationProcess.setText("1+6=");
        jTextFieldOperationProcess.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jTextFieldOperationProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOperationProcessActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("RAIZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSymbolClearEverything.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolClearEverything.setText("CE");
        jButtonSymbolClearEverything.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolClearEverythingActionPerformed(evt);
            }
        });

        jButtonSymbolClear.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolClear.setText("C");
        jButtonSymbolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolClearActionPerformed(evt);
            }
        });

        jButtonSymbolErase.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolErase.setText("Erase");

        jTextFieldDisplay.setEditable(false);
        jTextFieldDisplay.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setText("0");
        jTextFieldDisplay.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jTextFieldDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDisplayActionPerformed(evt);
            }
        });

        jButtonNumberFour.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberFour.setText("4");
        jButtonNumberFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberFourActionPerformed(evt);
            }
        });

        jButtonNumberFive.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberFive.setText("5");
        jButtonNumberFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberFiveActionPerformed(evt);
            }
        });

        jButtonNumberSix.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberSix.setText("6");
        jButtonNumberSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberSixActionPerformed(evt);
            }
        });

        jButtonSymbolMinus.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolMinus.setText("_");
        jButtonSymbolMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolMinusActionPerformed(evt);
            }
        });

        jButtonNumberSeven.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberSeven.setText("7");
        jButtonNumberSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberSevenActionPerformed(evt);
            }
        });

        jButtonNumberEight.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberEight.setText("8");
        jButtonNumberEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberEightActionPerformed(evt);
            }
        });

        jButtonNumberNine.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberNine.setText("9");
        jButtonNumberNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberNineActionPerformed(evt);
            }
        });

        jButtonSymbolMultiplication.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolMultiplication.setText("X");
        jButtonSymbolMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolMultiplicationActionPerformed(evt);
            }
        });

        jButtonSymbolMpdule.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolMpdule.setText("%");
        jButtonSymbolMpdule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolMpduleActionPerformed(evt);
            }
        });

        jButtonSymbolPowTwo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolPowTwo.setText("x^2");

        jButtonSymbolPow.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolPow.setText("^");
        jButtonSymbolPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolPowActionPerformed(evt);
            }
        });

        jButtonSymbolDivition.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolDivition.setText("/");
        jButtonSymbolDivition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolDivitionActionPerformed(evt);
            }
        });

        jButtonNumberOne.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberOne.setText("1");
        jButtonNumberOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberOneActionPerformed(evt);
            }
        });

        jButtonNumberTwo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberTwo.setText("2");
        jButtonNumberTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberTwoActionPerformed(evt);
            }
        });

        jButtonNumberThree.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberThree.setText("3");
        jButtonNumberThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberThreeActionPerformed(evt);
            }
        });

        jButtonSymbolPlus.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolPlus.setText("+");
        jButtonSymbolPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolPlusActionPerformed(evt);
            }
        });

        jButton21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton21.setText(".");

        jButtonNumberZero.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonNumberZero.setText("0");
        jButtonNumberZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumberZeroActionPerformed(evt);
            }
        });

        jButton23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton23.setText(".");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButtonSymbolEqual.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonSymbolEqual.setText("=");
        jButtonSymbolEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSymbolEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldOperationProcess)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolClearEverything, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolErase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNumberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNumberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonSymbolMpdule, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolPowTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolPow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolDivition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNumberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonNumberZero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButtonSymbolEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldOperationProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolClearEverything, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolErase, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSymbolMpdule, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolPowTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolPow, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolDivition, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumberZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSymbolEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOperationProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOperationProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOperationProcessActionPerformed

    private void jTextFieldDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDisplayActionPerformed

    private void jButtonSymbolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolClearActionPerformed
        // TODO add your handling code here:
        clearScreenValues();        
    }//GEN-LAST:event_jButtonSymbolClearActionPerformed

    private void jButtonSymbolClearEverythingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolClearEverythingActionPerformed
        // TODO add your handling code here:
        clearScreenValues();
    }//GEN-LAST:event_jButtonSymbolClearEverythingActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButtonNumberSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberSixActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("6");

    }//GEN-LAST:event_jButtonNumberSixActionPerformed

    private void jButtonNumberOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberOneActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("1");

    }//GEN-LAST:event_jButtonNumberOneActionPerformed

    private void jButtonNumberTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberTwoActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("2");
    }//GEN-LAST:event_jButtonNumberTwoActionPerformed

    private void jButtonNumberThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberThreeActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("3");
    }//GEN-LAST:event_jButtonNumberThreeActionPerformed

    private void jButtonNumberFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberFourActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("4");
        
    }//GEN-LAST:event_jButtonNumberFourActionPerformed

    private void jButtonNumberFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberFiveActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("5");
        
    }//GEN-LAST:event_jButtonNumberFiveActionPerformed

    private void jButtonNumberSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberSevenActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("7");
    }//GEN-LAST:event_jButtonNumberSevenActionPerformed

    private void jButtonNumberEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberEightActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("8");
    }//GEN-LAST:event_jButtonNumberEightActionPerformed

    private void jButtonNumberNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberNineActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("9");
    }//GEN-LAST:event_jButtonNumberNineActionPerformed

    private void jButtonNumberZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumberZeroActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("0");
    }//GEN-LAST:event_jButtonNumberZeroActionPerformed

    private void jButtonSymbolPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolPlusActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("+");
        this.currentOperation = "+";
    }//GEN-LAST:event_jButtonSymbolPlusActionPerformed

    private void jButtonSymbolMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolMinusActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("-");
        this.currentOperation = "-";        
    }//GEN-LAST:event_jButtonSymbolMinusActionPerformed

    private void jButtonSymbolMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolMultiplicationActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("x");
        this.currentOperation = "x";        
    }//GEN-LAST:event_jButtonSymbolMultiplicationActionPerformed

    private void jButtonSymbolDivitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolDivitionActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("/");
        this.currentOperation = "/";        
    }//GEN-LAST:event_jButtonSymbolDivitionActionPerformed

    private void jButtonSymbolMpduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolMpduleActionPerformed
        // TODO add your handling code here:
        dynamicChangeDisplayValue("%");
        this.currentOperation = "%";        
    }//GEN-LAST:event_jButtonSymbolMpduleActionPerformed

    private void jButtonSymbolEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolEqualActionPerformed
        // TODO add your handling code here:
        // TODO: check only 1 operation in display
        String operationProcess = this.jTextFieldDisplay.getText()+"="; // or this.displayText
        this.jTextFieldOperationProcess.setText(operationProcess);
//        System.out.println("DISPLAY TEXT");
//        System.out.println(displayText);
//        System.out.println("OPERATION");
//        System.out.println(this.currentOperation);
        String pattern = "";
        switch (this.currentOperation) {
            case "+":
                pattern = "\\+";
                break;
            case "-":
                pattern = "-";
                break;
            case "x":
                pattern = "x";
                break;
            case "/":
                pattern = "/";
                break;
           case "^":
                pattern = "\\^";
                break;          
            case "%":
                pattern = "%";
                break;                  
            default:
                throw new AssertionError();
        }
        
        String[] separateValues = displayText.split(pattern);
//        System.out.println("SEPARATE VALUES");
//        for (String sep: separateValues){
//            System.out.println("SEP");
//            System.out.println(sep);
//        }
        String firstValueString = separateValues[0];
        // TODO: use last element
        String secondValueString = separateValues[1];
        System.out.println("FIRST VALUE");
        System.out.println(firstValueString);
        System.out.println("SECOND VALUE");
        System.out.println(secondValueString);
        double firstValue = Double.parseDouble(firstValueString);
        double secondValue = Double.parseDouble(secondValueString);
        
        calc.setValue1(firstValue);
        calc.setValue2(secondValue);
        String result = "";
        switch (this.currentOperation) {
            case "+":
                result = String.valueOf(calc.add());
                break;
            case "-":
                result = String.valueOf(calc.substract());
                break;
            case "x":
                result = String.valueOf(calc.multiply());
                break;
            case "/":
                result = String.valueOf(calc.divide());
                break;
            case "^":
                result = String.valueOf(calc.pow());
                break;                
            case "%":
                result = String.valueOf(calc.modulus());
                break;                
                
            default:
                throw new AssertionError();
        }
//        this.jTextFieldDisplay.setText("");
        this.jTextFieldDisplay.setText(result);
        this.displayText = "";
    }//GEN-LAST:event_jButtonSymbolEqualActionPerformed

    private void jButtonSymbolPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSymbolPowActionPerformed
        // TODO add your handling code here:
        this.currentOperation = "^";
        dynamicChangeDisplayValue("^");
        
    }//GEN-LAST:event_jButtonSymbolPowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.currentOperation = "sqr";
        String firstValueToSquareString = this.displayText;
        double firstValueToSquare = Double.parseDouble(firstValueToSquareString);
        this.jTextFieldOperationProcess.setText("sqr("+firstValueToSquareString+")");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButtonNumberEight;
    private javax.swing.JButton jButtonNumberFive;
    private javax.swing.JButton jButtonNumberFour;
    private javax.swing.JButton jButtonNumberNine;
    private javax.swing.JButton jButtonNumberOne;
    private javax.swing.JButton jButtonNumberSeven;
    private javax.swing.JButton jButtonNumberSix;
    private javax.swing.JButton jButtonNumberThree;
    private javax.swing.JButton jButtonNumberTwo;
    private javax.swing.JButton jButtonNumberZero;
    private javax.swing.JButton jButtonSymbolClear;
    private javax.swing.JButton jButtonSymbolClearEverything;
    private javax.swing.JButton jButtonSymbolDivition;
    private javax.swing.JButton jButtonSymbolEqual;
    private javax.swing.JButton jButtonSymbolErase;
    private javax.swing.JButton jButtonSymbolMinus;
    private javax.swing.JButton jButtonSymbolMpdule;
    private javax.swing.JButton jButtonSymbolMultiplication;
    private javax.swing.JButton jButtonSymbolPlus;
    private javax.swing.JButton jButtonSymbolPow;
    private javax.swing.JButton jButtonSymbolPowTwo;
    private javax.swing.JTextField jTextFieldDisplay;
    private javax.swing.JTextField jTextFieldOperationProcess;
    // End of variables declaration//GEN-END:variables
}
