/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeli4m.eparcial1;


/**
 *
 * @author HP
 */

//import java.net.URL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableModel;
public class Interface extends javax.swing.JFrame {
    DefaultTableModel studentsModel;
    private float greaterAverage = 0.0f; 
    private List<Float> listOfAverages = new ArrayList<Float>();
    /**
     * Creates new form Interface
     */
    
    
    
    public void setupStudentsTableColumnsWidth(){
        jTableStudents.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableStudents.getColumnModel().getColumn(1).setPreferredWidth(200);     
        // set width for nota and credits
        for (int k=2;k<8;k++){
            jTableStudents.getColumnModel().getColumn(k).setPreferredWidth(50);                    
        }
        
        jTableStudents.setPreferredScrollableViewportSize(jTableStudents.getPreferredSize());
    }
    
    public void initStudentsTableModel(){
        String[] columnNames = {
                "N", "Apellidos y nombres", "Nota 1", "Credito 1", "Nota 2", "Credito 2", "Nota 3", "Credito 3", "Prom. simple", "Prom. ponderado"};
        Object[][] data = {
            { "1", "Morely Hinostroza Carlos", "16", "3", "18", "4", "19", "4", "17.5", "18" },
            { "2", "Cristina Torres Maldonado", "18", "3", "14", "4", "8", "4", "11.5", "12" },
            { "3", "Alberto Ramon Fernandez", "15", "3", "16", "4", "20", "4", "17.5", "17" }
        };        
        // null or data to instantiate Model
        studentsModel = new DefaultTableModel(null,columnNames);
        
        jTableStudents.setModel(studentsModel);
    }
    
    public void updateGreaterAverage(String nameStudent){
        
        for (int i = 0; i < listOfAverages.size(); i++) {
            float value = listOfAverages.get(i);
            if(value>greaterAverage){
                greaterAverage = value;
                jLabelBestStudentScore.setText(String.valueOf(greaterAverage));
                jLabelBestStudentName.setText(nameStudent);                
            }
        }

        System.out.println("GREATER IS: "+greaterAverage);
        // TODO: Improve greater average seelction and update 
    }
    
    public Interface() {
        initComponents();
        initStudentsTableModel();
        setupStudentsTableColumnsWidth();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldScore1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldScore2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldScore3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCredit1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCredit2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCredit3 = new javax.swing.JTextField();
        jButtonSaveData = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelBestStudentName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelBestStudentScore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        jLabel1.setText("DATOS DEL ESTUDIANTE");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setText("Apellidos y nombres");

        jTextFieldName.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldName.setToolTipText("");
        jTextFieldName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldScore1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldScore1.setToolTipText("");
        jTextFieldScore1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldScore1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Nota 1");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel4.setText("Nota 2");

        jTextFieldScore2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldScore2.setToolTipText("");
        jTextFieldScore2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldScore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldScore2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setText("Nota 3");

        jTextFieldScore3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldScore3.setToolTipText("");
        jTextFieldScore3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldScore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldScore3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setText("Credito 1");

        jTextFieldCredit1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldCredit1.setToolTipText("");
        jTextFieldCredit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCredit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCredit1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setText("Credito 2");

        jTextFieldCredit2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldCredit2.setToolTipText("");
        jTextFieldCredit2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCredit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCredit2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setText("Credito 3");

        jTextFieldCredit3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldCredit3.setToolTipText("");
        jTextFieldCredit3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCredit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCredit3ActionPerformed(evt);
            }
        });

        jButtonSaveData.setBackground(new java.awt.Color(233, 69, 96));
        jButtonSaveData.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonSaveData.setForeground(java.awt.Color.white);
        jButtonSaveData.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documentos\\NetBeansProjects\\sem4Ciclo2\\src\\main\\java\\com\\codeli4m\\sem4ciclo2\\add_data_icon.png")); // NOI18N
        jButtonSaveData.setText("GUARDAR DATOS");
        jButtonSaveData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 16));
        jButtonSaveData.setBorderPainted(false);
        jButtonSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDataActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(83, 52, 131));
        jButtonClear.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonClear.setForeground(java.awt.Color.white);
        jButtonClear.setText("LIMPIAR");
        jButtonClear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 24, 1, 24));
        jButtonClear.setBorderPainted(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(15, 52, 96));
        jPanel1.setForeground(new java.awt.Color(15, 52, 96));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("REPORTE DEL MEJOR ESTUDIANTE");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Apellidos y nombres");

        jLabelBestStudentName.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelBestStudentName.setForeground(java.awt.Color.white);
        jLabelBestStudentName.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("El mayor promedio ponderado");

        jLabelBestStudentScore.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelBestStudentScore.setForeground(java.awt.Color.white);
        jLabelBestStudentScore.setMinimumSize(new java.awt.Dimension(6, 20));
        jLabelBestStudentScore.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelBestStudentScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelBestStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBestStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBestStudentScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTableStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N", "Apellidos y nombres", "Nota 1", "Credito 1", "Nota 2", "Credito 2", "Nota 3", "Credito 3", "Prom. simple", "Prom. ponderado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStudents.setRowHeight(24);
        jTableStudents.getTableHeader().setResizingAllowed(false);
        jTableStudents.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCredit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextFieldCredit2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jTextFieldCredit3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonSaveData, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCredit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCredit2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCredit3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldScore1ActionPerformed

    private void jTextFieldScore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldScore2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldScore2ActionPerformed

    private void jTextFieldScore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldScore3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldScore3ActionPerformed

    private void jTextFieldCredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCredit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCredit1ActionPerformed

    private void jTextFieldCredit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCredit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCredit2ActionPerformed

    private void jTextFieldCredit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCredit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCredit3ActionPerformed

    private boolean isFloat(String value){
        boolean res = false;
        try {
            float floatValue = Float.parseFloat(value);
            res = true;
        } catch (Exception e) {
            res = false;
        }
        return res;
    }
    
    private boolean isValidUsername(String username){
        int usernameLen = username.length();
        return (usernameLen >= 0 && usernameLen <= 255);
    }
    
    private void jButtonSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDataActionPerformed
        String stName = jTextFieldName.getText();
        String stScore1 = jTextFieldScore1.getText();
        String stScore2 = jTextFieldScore2.getText();
        String stScore3 = jTextFieldScore3.getText();
        String stCredit1 = jTextFieldCredit1.getText();
        String stCredit2 = jTextFieldCredit2.getText();
        String stCredit3 = jTextFieldCredit3.getText();

        // TODO: input validation
        if (isValidUsername(stName) && isFloat(stScore1) && isFloat(stScore2) && isFloat(stScore3) && isFloat(stCredit1) && isFloat(stCredit2) && isFloat(stCredit3)){
        Student student = new Student(stName, Float.parseFloat(stScore1), Float.parseFloat(stScore2), Float.parseFloat(stScore3), Float.parseFloat(stCredit1), Float.parseFloat(stCredit2), Float.parseFloat(stCredit3));

        listOfAverages.add(Float.parseFloat(String.valueOf(student.getPonderedAverage())));

        updateGreaterAverage(student.getFullNameString());

        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(2);
        
        int numberOfNextRow = studentsModel.getRowCount()+1;
        String[] studentData = {
            String.valueOf(numberOfNextRow),
            student.getFullNameString(),
            String.valueOf(student.getScore1()),
            String.valueOf(student.getCredit1()),
            String.valueOf(student.getScore2()),
            String.valueOf(student.getCredit2()),
            String.valueOf(student.getScore3()),
            String.valueOf(student.getCredit3()),
            String.valueOf(df.format(student.getSimpleAverage())),
            String.valueOf(df.format(student.getPonderedAverage())) };
        studentsModel.addRow(studentData);
        }
        else{
            JOptionPane.showMessageDialog(null, "Verifica los datos ingresados. Solo se permiten numeros decimales");
        }
    }//GEN-LAST:event_jButtonSaveDataActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldName.setText("");
        jTextFieldScore1.setText("");
        jTextFieldScore2.setText("");
        jTextFieldScore3.setText("");
        jTextFieldCredit1.setText("");
        jTextFieldCredit2.setText("");
        jTextFieldCredit3.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSaveData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBestStudentName;
    private javax.swing.JLabel jLabelBestStudentScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudents;
    private javax.swing.JTextField jTextFieldCredit1;
    private javax.swing.JTextField jTextFieldCredit2;
    private javax.swing.JTextField jTextFieldCredit3;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldScore1;
    private javax.swing.JTextField jTextFieldScore2;
    private javax.swing.JTextField jTextFieldScore3;
    // End of variables declaration//GEN-END:variables
}