/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeli4m.testfarmacia.gui;

/**
 *
 * @author HP
 */

import com.codeli4m.testfarmacia.database.DBProductosController;

import com.codeli4m.testfarmacia.database.AuthenticatedUser;
import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;

public class ProductosInterface extends javax.swing.JFrame {

    DefaultTableModel productsResumenModel;
    DBProductosController dbProductsController =  new DBProductosController();
    AuthenticatedUser authenticatedUser;
    /**
     * Creates new form ProductosInterface
     */
    public ProductosInterface() {
        initComponents();
        initProductsTableModel();
    }
    
    private void setupProductsTableRowsWidth(){
        jTableResumenProductos.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableResumenProductos.getColumnModel().getColumn(1).setPreferredWidth(140);

        jTableResumenProductos.setRowHeight(30);
    }
    
    private void initProductsTableModel(){
                String[] columnNames = {
                "Codigo", "Nombre", "Precio compra", "Categoria ID", "Stock actual", "Medida", "Cant. medida"};
        Object[][] data = {
            { "3200", "Salbutamol", "150.40", "102", "60", "unidad", "20" } // ,
//            { "2", "Cristina Torres Maldonado", "18", "3", "14", "4", "8", "4", "11.5", "12" },
//            { "3", "Alberto Ramon Fernandez", "15", "3", "16", "4", "20", "4", "17.5", "17" }
        };        
        // null or data to instantiate Model
        productsResumenModel = new DefaultTableModel(data,columnNames);
        jTableResumenProductos.setModel(productsResumenModel);
        setupProductsTableRowsWidth();
    }
    
    public void setupAuthorizationControl(){
        String userName = this.authenticatedUser.name;
        String userNickName = this.authenticatedUser.nickname;
        String userRol = this.authenticatedUser.rol;
        System.out.println("***** SETUP USER INFORMATION *****");
        System.out.println(userName+" - "+userNickName+" - "+userRol+" - ");
        this.jLabelUserName.setText(userName);
        this.jLabelUserNickname.setText(userNickName);
        this.jLabelUserRol.setText(userRol);

        if (userRol.equalsIgnoreCase("invitado")){
            this.jTabbedPaneProductos.setEnabledAt(1, false);
            this.jTabbedPaneProductos.setEnabledAt(3, false);
            this.jTabbedPaneProductos.setEnabledAt(4, false);
        }
    }
    
    public void setAuthenticatedUser(AuthenticatedUser authUser){
        System.out.println("---- AUTHENTICATED USER RECEIVED ----");
        this.authenticatedUser = authUser;
        setupAuthorizationControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProductos = new javax.swing.JTabbedPane();
        jPanelUserInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserNickname = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelUserRol = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelProductosCreate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCrearNombre = new javax.swing.JTextField();
        jTextFieldCrearPrecioCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCategoriaID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCrearPresentacionID = new javax.swing.JTextField();
        jTextFieldCrearStockActual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCrearNumeroLote = new javax.swing.JTextField();
        jTextFieldFechaVenc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCrearUnidadMedida = new javax.swing.JTextField();
        jTextFieldUnidadMedida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonAddProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldCrearDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButtonCheck = new javax.swing.JButton();
        jPanelProductosRead = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResumenProductos = new javax.swing.JTable();
        jButtonAddDataTest = new javax.swing.JButton();
        jButtonRefreshProductsInfo = new javax.swing.JButton();
        jPanelProductosUpdate = new javax.swing.JPanel();
        jPanelProductosDelete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("BIENVENIDO");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel14.setText("Nombre :");

        jLabelUserName.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelUserName.setText("Liam Quinones");

        jLabelUserNickname.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelUserNickname.setText("nickname");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel17.setText("Nickname :");

        jLabelUserRol.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelUserRol.setText("rol sample");

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel19.setText("Rol :");

        javax.swing.GroupLayout jPanelUserInfoLayout = new javax.swing.GroupLayout(jPanelUserInfo);
        jPanelUserInfo.setLayout(jPanelUserInfoLayout);
        jPanelUserInfoLayout.setHorizontalGroup(
            jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserInfoLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelUserInfoLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUserRol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelUserInfoLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelUserInfoLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelUserNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanelUserInfoLayout.setVerticalGroup(
            jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addGroup(jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelUserName))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelUserNickname))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabelUserRol))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPaneProductos.addTab("USER INFO", jPanelUserInfo);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Crear productos");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Nombre ");

        jTextFieldCrearNombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCrearNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCrearNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrearNombreActionPerformed(evt);
            }
        });

        jTextFieldCrearPrecioCompra.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCrearPrecioCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCrearPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrearPrecioCompraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setText("Precio compra ");

        jTextFieldCategoriaID.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCategoriaID.setText("103");
        jTextFieldCategoriaID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCategoriaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategoriaIDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setText("Categoria ID");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setText("Presentacion ID");

        jTextFieldCrearPresentacionID.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCrearPresentacionID.setText("11");
        jTextFieldCrearPresentacionID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCrearPresentacionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrearPresentacionIDActionPerformed(evt);
            }
        });

        jTextFieldCrearStockActual.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCrearStockActual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCrearStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrearStockActualActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setText("Stock actual");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel9.setText("Numero lote");

        jTextFieldCrearNumeroLote.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCrearNumeroLote.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCrearNumeroLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrearNumeroLoteActionPerformed(evt);
            }
        });

        jTextFieldFechaVenc.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldFechaVenc.setText("12/12/2023");
        jTextFieldFechaVenc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldFechaVenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaVencActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setText("Fecha venc.");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel11.setText("Unidad medida");

        jTextFieldCrearUnidadMedida.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldCrearUnidadMedida.setText("unidad");
        jTextFieldCrearUnidadMedida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldCrearUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrearUnidadMedidaActionPerformed(evt);
            }
        });

        jTextFieldUnidadMedida.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextFieldUnidadMedida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextFieldUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnidadMedidaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel12.setText("Cantidad unidad");

        jButtonAddProduct.setBackground(java.awt.Color.red);
        jButtonAddProduct.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonAddProduct.setForeground(java.awt.Color.white);
        jButtonAddProduct.setText("AGREGAR");
        jButtonAddProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));

        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jTextFieldCrearDescripcion.setColumns(20);
        jTextFieldCrearDescripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldCrearDescripcion.setRows(5);
        jTextFieldCrearDescripcion.setAutoscrolls(false);
        jTextFieldCrearDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jScrollPane1.setViewportView(jTextFieldCrearDescripcion);

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setText("Descripcion");

        jButtonCheck.setBackground(java.awt.Color.orange);
        jButtonCheck.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonCheck.setForeground(java.awt.Color.white);
        jButtonCheck.setText("CHECK");
        jButtonCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductosCreateLayout = new javax.swing.GroupLayout(jPanelProductosCreate);
        jPanelProductosCreate.setLayout(jPanelProductosCreateLayout);
        jPanelProductosCreateLayout.setHorizontalGroup(
            jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCrearNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCrearPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCrearStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCrearNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCrearPresentacionID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCrearUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );
        jPanelProductosCreateLayout.setVerticalGroup(
            jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCrearNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCrearPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldCrearStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldCrearNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCheck)
                        .addGap(22, 22, 22))
                    .addGroup(jPanelProductosCreateLayout.createSequentialGroup()
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldCrearPresentacionID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCrearUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        jTabbedPaneProductos.addTab("CREATE", jPanelProductosCreate);

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel15.setText("RESUMEN DE PRODUCTOS");

        jTableResumenProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableResumenProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio Compra", "Categoria ID", "Stock actual", "Unidad medida", "Cantidad Medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResumenProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableResumenProductos);
        if (jTableResumenProductos.getColumnModel().getColumnCount() > 0) {
            jTableResumenProductos.getColumnModel().getColumn(0).setResizable(false);
            jTableResumenProductos.getColumnModel().getColumn(1).setResizable(false);
            jTableResumenProductos.getColumnModel().getColumn(2).setResizable(false);
            jTableResumenProductos.getColumnModel().getColumn(3).setResizable(false);
            jTableResumenProductos.getColumnModel().getColumn(4).setResizable(false);
            jTableResumenProductos.getColumnModel().getColumn(5).setResizable(false);
            jTableResumenProductos.getColumnModel().getColumn(6).setResizable(false);
        }

        jButtonAddDataTest.setBackground(java.awt.Color.green);
        jButtonAddDataTest.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAddDataTest.setForeground(java.awt.Color.black);
        jButtonAddDataTest.setText("Add data test");
        jButtonAddDataTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDataTestActionPerformed(evt);
            }
        });

        jButtonRefreshProductsInfo.setBackground(java.awt.Color.blue);
        jButtonRefreshProductsInfo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonRefreshProductsInfo.setText("Refresh productos info");
        jButtonRefreshProductsInfo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonRefreshProductsInfoFocusGained(evt);
            }
        });
        jButtonRefreshProductsInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshProductsInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductosReadLayout = new javax.swing.GroupLayout(jPanelProductosRead);
        jPanelProductosRead.setLayout(jPanelProductosReadLayout);
        jPanelProductosReadLayout.setHorizontalGroup(
            jPanelProductosReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosReadLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButtonRefreshProductsInfo)
                .addGap(225, 225, 225)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddDataTest)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductosReadLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanelProductosReadLayout.setVerticalGroup(
            jPanelProductosReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosReadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelProductosReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButtonAddDataTest)
                    .addComponent(jButtonRefreshProductsInfo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneProductos.addTab("READ", jPanelProductosRead);

        javax.swing.GroupLayout jPanelProductosUpdateLayout = new javax.swing.GroupLayout(jPanelProductosUpdate);
        jPanelProductosUpdate.setLayout(jPanelProductosUpdateLayout);
        jPanelProductosUpdateLayout.setHorizontalGroup(
            jPanelProductosUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        jPanelProductosUpdateLayout.setVerticalGroup(
            jPanelProductosUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        jTabbedPaneProductos.addTab("UPDATE", jPanelProductosUpdate);

        javax.swing.GroupLayout jPanelProductosDeleteLayout = new javax.swing.GroupLayout(jPanelProductosDelete);
        jPanelProductosDelete.setLayout(jPanelProductosDeleteLayout);
        jPanelProductosDeleteLayout.setHorizontalGroup(
            jPanelProductosDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        jPanelProductosDeleteLayout.setVerticalGroup(
            jPanelProductosDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        jTabbedPaneProductos.addTab("DELETE", jPanelProductosDelete);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("SECCION PRODUCTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jTabbedPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneProductos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCrearNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrearNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrearNombreActionPerformed

    private void jTextFieldCrearPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrearPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrearPrecioCompraActionPerformed

    private void jTextFieldCategoriaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoriaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategoriaIDActionPerformed

    private void jTextFieldCrearPresentacionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrearPresentacionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrearPresentacionIDActionPerformed

    private void jTextFieldCrearStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrearStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrearStockActualActionPerformed

    private void jTextFieldCrearNumeroLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrearNumeroLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrearNumeroLoteActionPerformed

    private void jTextFieldFechaVencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaVencActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaVencActionPerformed

    private void jTextFieldCrearUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrearUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrearUnidadMedidaActionPerformed

    private void jTextFieldUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUnidadMedidaActionPerformed

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
        // TODO add your handling code here:
        System.out.println("CHECK BUTTON PRESSED");
//        new DBProductosController().listProducts();
//(String productoNombre, String productoDescripcion, float productoPrecioCompra, int categoriaId, int presentacionId, int productoStockActual, String productoLote, String productoFechaVenc, String productoUnidadMedida, int productoCantidadUnidades){
        dbProductsController.insertNewProduct("Antalgina 100 mg", "Para sintomas de la fiebre", 14.5f, 103, 11, 20, "1085218", "24/12/2023", "unidades", 10);
        // adding elements from db
    }//GEN-LAST:event_jButtonCheckActionPerformed

    private void addRowsFromListStringArrayToTableModel(List<String[]> vectorObject){
        for (String[] vectorObjectItem : vectorObject) {
            this.productsResumenModel.addRow(vectorObjectItem);
        }
    }
    
    private void jButtonAddDataTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDataTestActionPerformed
        // TODO add your handling code here:
//        String[][] testData = {
//            { "3007", "Salbutamol", "150.40", "102", "11", "60", "3688019", "2023-02-04", "unidad", "20" },
//            { "3008", "Salbutamol", "150.40", "102", "11", "60", "3688019", "2023-02-04", "unidad", "20" },
//            { "3009", "Salbutamol", "150.40", "102", "11", "60", "3688019", "2023-02-04", "unidad", "20" }
//        };
                List<String[]> testListData = new ArrayList<String[]>();
        String[] item1= { "4004", "Salbutamol", "150.40", "102", "60", "unidad", "20" };
        String[] item2= { "4005", "Salbutamol", "150.40", "102", "60", "unidad", "20" };
        String[] item3= { "4006", "Salbutamol", "150.40", "102", "60", "unidad", "20" };
        testListData.add(item1);
        testListData.add(item2);
        testListData.add(item3);
//        productsResumenModel.addRow(testData[0]);
        this.addRowsFromListStringArrayToTableModel(testListData);
    }//GEN-LAST:event_jButtonAddDataTestActionPerformed

    private void jButtonRefreshProductsInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshProductsInfoActionPerformed
        // TODO add your handling code here:
        List<String[]> testInfo = dbProductsController.getBasicInfoProducts();
        this.addRowsFromListStringArrayToTableModel(testInfo);
    }//GEN-LAST:event_jButtonRefreshProductsInfoActionPerformed

    private void jButtonRefreshProductsInfoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonRefreshProductsInfoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshProductsInfoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDataTest;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonRefreshProductsInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserNickname;
    private javax.swing.JLabel jLabelUserRol;
    private javax.swing.JPanel jPanelProductosCreate;
    private javax.swing.JPanel jPanelProductosDelete;
    private javax.swing.JPanel jPanelProductosRead;
    private javax.swing.JPanel jPanelProductosUpdate;
    private javax.swing.JPanel jPanelUserInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneProductos;
    private javax.swing.JTable jTableResumenProductos;
    private javax.swing.JTextField jTextFieldCategoriaID;
    private javax.swing.JTextArea jTextFieldCrearDescripcion;
    private javax.swing.JTextField jTextFieldCrearNombre;
    private javax.swing.JTextField jTextFieldCrearNumeroLote;
    private javax.swing.JTextField jTextFieldCrearPrecioCompra;
    private javax.swing.JTextField jTextFieldCrearPresentacionID;
    private javax.swing.JTextField jTextFieldCrearStockActual;
    private javax.swing.JTextField jTextFieldCrearUnidadMedida;
    private javax.swing.JTextField jTextFieldFechaVenc;
    private javax.swing.JTextField jTextFieldUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
